name: 'Org Action'
description: 'Github action for preparing org-level github token and git checkout using github app secrets'
inputs:
  app_id:
    description: "default env.GITHUB_APP_ID"
  app_private_key:
    description: "default env.GITHUB_APP_PRIVATE_KEY"
  app_permission:
    description: >
      comma-seperated value, supported: 
      - `contents-ro` : git checkout permission
      - `contents-rw` : git commit and permission, it contains contents-ro also
      - `actions-rw` : github actions(workflow) read and execute permission
      - `checks-rw` : github checks read and write permission
    default: "contents-ro"
  checkout:
    description: |
      multiline-input, formatted "<repository>@<ref>: <checkout path>"
      
      repository should exist in same owner of workflow's and able to read with github app token
      <repository> should be repository name without owner or `<owner>/<name>`
      
      `@<ref>` can be omitted and uses `main` branch by default.
      if repository is same with workflow's and @ref is omitted, it uses github.ref instead.
      
      be caution order of the lines, this actions delete path before checkout to avoid conflict.
      outer path should be defined first and inner path should be defined last.
      
      for example,
      ```yaml
      with:
        checkout:
          ab180/web-server: .
          ab180/common-lib: ./lib/common-lib
      ```
    default: ""
  cwd:
    description: "current working directory."
    default: ${{github.workspace}}
  add_git_config:
    description: "add github app token into git config to use when checkout organization repository"
    default: 'true'
  action_token:
    description: "token used when check out itself"
    default: ${{ github.token }}
  fetch-depth:
    description: "number of commits to fetch. 0 indicates all history for all branches and tags."
    default: 1
outputs:
  token:
    description: "github app token, it is also exported to environment named as `GITHUB_APP_TOKEN` and can be used in same job"

runs:
  using: node16
  main: dist/index.js
